version: '3'
services:
  app:
    build: .
    ports:
      - "5001:5001"  # Expose app on port 5000

  prometheus:
    image: prom/prometheus
    ports:
      - "9095:9090"  # Expose Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3005:3000"  # Expose Grafana UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set Grafana admin password
