global:
  scrape_interval: 15s  # How often to scrape targets by default

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['app:5001']  # Replace 'app' with the service name defined in docker-compose.yml

